### ISSUE TITLE
Iron powder in blast furnace

### ISSUE THREAD

**Issue by Pfidget** [kwpugh/PowderPower#1]
I could not get the iron powder to smelt in the blast furnace. It worked just fine in the regular furnace though. 

Forge 20.0.40
mod version 1.14.4-3.0.8

**Comment by kwpugh** [comment]
Thanks for reporting.  I had only added furnace recipes.  I will add blast furnace recipes for iron, gold, redium, Lapium, gemium and trilium in next update.

**Comment by kwpugh** [comment]
Addressed in version 3.0.10.

**Comment by Pfidget** [comment]
Thank you for taking care of this so quickly :)
