### ISSUE TITLE
Ore dict. for 1.15.2

### ISSUE THREAD

**Issue by grandogarndo** [kwpugh/PowderPower#14]
I have downloaded 1.15.2.-3.1.68 and whenever i try to use jei to make a recipe in anything other than my inventory or a crafting table Redstone is not considered ore-dictionaried, so it just places nothing in even though Redstone is in the system. I cannot use this mod when i want to automate anything and hope you can find a way to fix this cause it is an awesome idea.

**Comment by kwpugh** [comment]
Are you asking for Minecraft Redstone and my Redstone Powder to be interchangeable?

**Comment by grandogarndo** [comment]
Sorry, it seems that refined storage is being messed up by a brewing mod or something where it doesn't auto-input when you click on the plus in JEI
