### ISSUE TITLE
[1.16.5] Dragon Token is bugged

### ISSUE THREAD

**Issue by antibang** [kwpugh/PowderPower#17]
I recently updated to Forge 36.1.0 plus the newest version of the mod and a few friends and I have noticed when we have the Dragon Token in any of our belt slots then leave the server or single player worlds that it will be in our inventory when we come back to the game. Sometimes, it will still be in the original slot, but when you go to remove it, it vanishes. It just seems really glitchy right now. Didn't have any issues with it until I updated.

**Comment by kwpugh** [comment]
This sounds like it is an issue with Curios.   What version of Curios are you using.   Does this happen with any other items placed in Curios slots?

**Comment by antibang** [comment]
Curios totally slipped my mind. But it's only the dragon token :( we can have every slot filled, but it's only that one that gets kicked out. Curios version is 4.0.5.0

**Comment by kwpugh** [comment]
I still cannot replicate this issue.

**Comment by antibang** [comment]
Darn :( I tried a bunch of different things myself just to see if it was mods colliding with each other, but nothing seemed to make a difference. Would a debug or anything help??

**Comment by kwpugh** [comment]
Just to double check, you do have Curios installed on both the client and the server?

**Comment by kwpugh** [comment]
Try this version and let me know if it works correctly.

[PowderPower-Forge-1.16.5-3.2.33.jar.zip](https://github.com/kwpugh/PowderPower/files/6307353/PowderPower-Forge-1.16.5-3.2.33.jar.zip)

**Comment by antibang** [comment]
I do and I just tried that version and it's still doing the same thing :(

**Comment by kwpugh** [comment]
I tested out v32 on my test server with forge 36.1.4, powder power, and curios and I cannot replicate the issue.

Something is conflicting with this and I have no idea what.

**Comment by kwpugh** [comment]
I checked in with a couple of servers that also use Powder Power and they have not seen this issue either.

**Comment by kwpugh** [comment]
Are you playing a custom or public modpack?

**Comment by antibang** [comment]
I know, I'm getting that vibe as well lol it's honestly not too big a deal for me and my friends haven't complained about it, so I can work around it. It's a public modpack. It's called BaerCraft if you intend on seeing if you're having the issue that way

**Comment by kwpugh** [comment]
Create a new game profile with forge 36.1.4 and the v33 of Powder Power and latest Curios.

Join server:  pughland.mcserver.us and test there to confirm.

**Comment by antibang** [comment]
I just updated Curios to 4.0.5.1 and it seemed to have fixed the issue :p I appreciate you taking so much time looking into this!
