### ISSUE TITLE
Powder Power Crash on Startup

### ISSUE THREAD

**Issue by ClaudiusMinimus** [kwpugh/PowderPower#19]
Yesterday, I had a player post this on my discord [crash-seaturtlemaster1-2023-01-21_10.14.57-fml.txt](https://github.com/kwpugh/powder_power_forge/files/10472830/crash-seaturtlemaster1-2023-01-21_10.14.57-fml.txt). His game crashed on the first launch after a fresh install. I asked him to attempt to relaunch the pack. This time the modpack opened just fine. I have also experienced this same issue in testing. It seems both times that Powder Power was the reason. My suspicion is something in the launch sequence is out of order. In both cases, the second launch appears to fix it.

Modpack: [Create on a Potato PC: Sky Edition](https://www.curseforge.com/minecraft/modpacks/create-on-a-potato-pc-sky/files/4348581)
Minecraft: 1.19.2
Forge: 43.2.3
Powder Power: 3.6.13

**Comment by kwpugh** [comment]
Good to know.  Not sure I can do much about how mods load within a modpack, but I will keep it for future reference.
