### ISSUE TITLE
Some armor perks not working

### ISSUE THREAD

**Issue by Oaurn** [kwpugh/PowderPower#2]
I'm playing the FTB Unstable pack and noticed an issue with armor perks.

Powder Powder version 1.14.4-3.0.36

The armor's perks are listed as thus:

Lapium Armor perks - water breathing and poison protection
Redium Armor perks - fire resistance and wither protection
Gemium Armor perks - water breathing, fire resistance, poison and wither protection, slow regeneration and no fall damage
Trillium Armor perks - water breathing, fire resistance, poison and wither protection, moderate regeneration and no fall damage

Lapium and Redium work as expected, but both the Gemium and Trillium don't actually provide any regen at all.  Water breathing, fire resist, poison/wither protection and fall damage protection all work just fine.

**Comment by kwpugh** [comment]
I will take a look this evening

**Comment by kwpugh** [comment]
I see the problem right off.  I will correct and push a new version this evening.

Thank you for reporting.

**Comment by kwpugh** [comment]
Fixed in the latest version.
