### ISSUE TITLE
JEI compat

### ISSUE THREAD

**Issue by Yoosk** [kwpugh/PowderPower#4]
It would be nice to get JEI compat for alchemist hammer, some players on our server are confused and think that there are no recipes for powders, since jei is not showing that you have to use hammer on ores to get them.

1.15.2

**Comment by kwpugh** [comment]
I will research how to do this.

**Comment by kwpugh** [comment]
![Screen Shot 2020-02-21 at 2 03 57 PM](https://user-images.githubusercontent.com/8809210/75067642-1c5da600-54b3-11ea-9057-3f9b42894d18.png)

Will this be sufficient?

**Comment by kwpugh** [comment]
Fixed in latest release.   Added JEI info pages for Alchemist Hammer and Alchemist Wand.
