### ISSUE TITLE
Few talisman is not working correctly

### ISSUE THREAD

**Issue by runescapejon** [kwpugh/PowderPower#5]
The Regeneration talisman is not working and that there are few others that it's just simply not working. What i mean by this is you have the talisman in your inventory it does nothing but just show that you have the effect. I assume because there no time that it's just 00:00 https://gyazo.com/c0114419f21e1ba4bac00cb3287bb737 here a screenshot of it. Also i am on `PowderPower-1.12.2_2.0.5` Thank you.

**Comment by kwpugh** [comment]
Sorry, 1.12.2 is no longer supported.   Please upgrade to 1.14.4 or 1.15.2.
