### ISSUE TITLE
[Suggestion] Block Conversion

### ISSUE THREAD

**Issue by kittenblackfriends** [kwpugh/PowderPower#8]
I would like to recommend that right clicking a Block of Emerald or a Block of Diamond results in a corresponding amount of their respective powders (9 each). I've started exploring this mod later in my playthrough and I already have a Fortune-Mending pick. I would also consider it for Redstone, Iron, and Lapis, as those block forms also exist.

**Comment by kwpugh** [comment]
Are you suggesting adding these features to the Alchemist Wand?

**Comment by kittenblackfriends** [comment]
Unfortunately, you need to be Gemium tier in order to make the alchemist wand. I went to go experiment with it this morning and could not craft it. If we could use the Alch Hammer to crush the Block of [Gemstone] or the mortar and pestle to crush the individual stones, that would make it much more accessible.

**Comment by kwpugh** [comment]
I'm not sure about this approach.   Diamonds I get, but obtaining emeralds in villages these day is pretty trivial, so a conversion from emerald block to powder would make Gemium very easy to get.  Not sure I want to ease the progression.

**Comment by kittenblackfriends** [comment]
I mean, I get both from sailing and raiding sunken ships and underwater ruins. If you want to make stuff difficult to obtain, I always have the most trouble getting to the End (because I'm a super safe player who doesn't go monster hunting for the required ender pearls).

Regardless, I do understand your point of view. It is difficult to balance this kind of stuff, because assuming someone is using your mod, they are using other mods that include autominers.

**Comment by kwpugh** [comment]
If you are more of a safer player, you might want to think about adding my Resourceful Tools mod to your game.   It provides safer ways to get mob drops like ender pearl, nether stars, and blaze powder, etc.

**Comment by kwpugh** [comment]
Since I am not going to be making any changes of this, I will be closing.
